"""
Regenerate XSD 1.0 companion schemas into ./types/xml/1.0.

Some IDEs (e.g. VS Code) do not support XSD 1.1,
so the hand-written 1.1 schemas in ./types/xml raise false errors there.
This script derives deliberately laxer 1.0 companions for IDE completion and
structural validation; pytest keeps validating against the 1.1 originals.

Transform:
  - Drop vc:* versioning attributes and every xs:assert.
  - Replace each element's xs:alternative set with one merged permissive type:
    an unbounded choice over all variants' particles plus
    the union of their attributes, all optional.
  - xs:error variants vanish.
  - Wildcard (xs:any) variants are skipped, as a wildcard next to named
    elements violates XSD 1.0's Unique Particle Attribution rule.
  - Same-named children whose declarations differ merge recursively into
    named merged.<name> types when every collider references a named
    complexType, else widen to xs:anyType (untyped, for attributes).
  - Invariant: the 1.0 schema never rejects a document the 1.1 schema accepts.
  - Unknown XSD 1.1 constructs abort - never silently emit a wrong schema.
"""

import copy
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import NoReturn

XS = "http://www.w3.org/2001/XMLSchema"
VC = "http://www.w3.org/2007/XMLSchema-versioning"

SRC = Path("types/xml")
OUT = Path("types/xml/1.0")
SCHEMAS: list[str] = ["addon.xsd", "settings.xsd"]

ET.register_namespace("xs", XS)


def xstag(local: str) -> str:
    return f"{{{XS}}}{local}"


MODEL_GROUPS: frozenset[str] = frozenset({xstag("sequence"), xstag("choice"), xstag("all")})
XS11_ONLY: frozenset[str] = frozenset(
    {
        xstag("override"),
        xstag("openContent"),
        xstag("defaultOpenContent"),
        xstag("assertion"),
    }
)
HEADER = (
    "<!-- GENERATED by scripts/xsd10.py from ../{name} - DO NOT EDIT.\n"
    "     XSD 1.0 companion for the IDE (LemMinX/Xerces has no XSD 1.1):\n"
    "     asserts dropped, conditional alternatives merged into permissive types.\n"
    "     Deliberately laxer than the 1.1 original, which stays the source of\n"
    "     truth (pytest validates against it). Regenerate: uv run poe xsd10 -->\n"
)


def fail(message: str) -> NoReturn:
    raise SystemExit(f"xsd10: {message}")


def canonical(node: ET.Element) -> bytes:
    """
    Node identity for dedup: occurrence counts, use= and whitespace ignored.
    """

    clone: ET.Element = copy.deepcopy(node)
    for attr in ("minOccurs", "maxOccurs", "use"):
        clone.attrib.pop(attr, None)

    for descendant in clone.iter():
        if descendant.text is not None and not descendant.text.strip():
            descendant.text = None
        if descendant.tail is not None and not descendant.tail.strip():
            descendant.tail = None

    return ET.tostring(clone)


def particles(node: ET.Element) -> list[ET.Element]:
    """
    Element declarations and group refs of a content model, in document order.

    Wildcards (xs:any) are dropped: under XSD 1.0's Unique Particle Attribution
    rule a wildcard cannot sit in one choice with named elements.
    """

    found: list[ET.Element] = []
    for child in node:
        if child.tag in MODEL_GROUPS:
            found.extend(particles(child))
        elif child.tag in (xstag("element"), xstag("group")):
            found.append(child)

    return found


def attribute_uses(ctype: ET.Element) -> list[ET.Element]:
    return [c for c in ctype if c.tag in (xstag("attribute"), xstag("attributeGroup"))]


def has_wildcard_content(ctype: ET.Element) -> bool:
    return any(node.tag == xstag("any") for node in ctype.iter())


class Merger:
    """
    Merges sets of named complexTypes into single permissive 1.0 types.
    """

    def __init__(self, root: ET.Element) -> None:
        self.root = root
        self.ctypes: dict[str, ET.Element] = {ct.get("name", ""): ct for ct in root.findall(xstag("complexType"))}
        self.generated: dict[frozenset[str], str] = {}

    def merge(self, variant_names: list[str]) -> ET.Element:
        """
        One anonymous complexType accepting everything the variants accept.
        """

        variants: list[ET.Element] = [self.ctypes[n] for n in variant_names]
        merged = ET.Element(xstag("complexType"))
        choice = ET.SubElement(merged, xstag("choice"), {"minOccurs": "0", "maxOccurs": "unbounded"})

        decls: dict[str, list[ET.Element]] = {}
        for variant in variants:
            for particle in particles(variant):
                name: str | None = particle.get("name") or particle.get("ref")
                if name is None:
                    fail("particle without name or ref")
                decls.setdefault(f"{particle.tag} {name}", []).append(particle)

        for group in decls.values():
            choice.append(self.merge_decls(group))

        if len(choice) == 0:
            merged.remove(choice)

        attrs: dict[str, list[ET.Element]] = {}
        for variant in variants:
            for use in attribute_uses(variant):
                key: str | None = use.get("name") or use.get("ref")
                if key is None:
                    fail("attribute without name or ref")
                attrs.setdefault(f"{use.tag} {key}", []).append(use)

        for group in attrs.values():
            merged.append(self.merge_attribute(group))

        return merged

    def merge_decls(self, decls: list[ET.Element]) -> ET.Element:
        first: ET.Element = decls[0]
        if all(canonical(d) == canonical(first) for d in decls[1:]):
            clone: ET.Element = copy.deepcopy(first)
            clone.attrib.pop("minOccurs", None)
            clone.attrib.pop("maxOccurs", None)
            return clone

        # Same-named element declared differently across variants: merge the
        # types recursively when all are named complexTypes, else widen to
        # xs:anyType - picking one variant would reject the others' documents.
        name: str | None = first.get("name")
        if first.tag != xstag("element") or name is None:
            fail(f"conflicting non-element declarations for {first.get('ref')}")

        type_names: list[str] = [d.get("type") or "" for d in decls]
        if all(t in self.ctypes for t in type_names):
            merged_name: str = self.merged_child_type(name, type_names)
            return ET.Element(xstag("element"), {"name": name, "type": merged_name})

        return ET.Element(xstag("element"), {"name": name})

    def merged_child_type(self, element_name: str, type_names: list[str]) -> str:
        key: frozenset[str] = frozenset(type_names)
        if key in self.generated:
            return self.generated[key]

        merged_name: str = f"merged.{element_name}"
        if merged_name in self.ctypes:
            fail(f"merged type name collision: {merged_name}")

        merged: ET.Element = self.merge(list(dict.fromkeys(type_names)))
        merged.set("name", merged_name)

        self.root.append(merged)
        self.ctypes[merged_name] = merged
        self.generated[key] = merged_name

        return merged_name

    def merge_attribute(self, decls: list[ET.Element]) -> ET.Element:
        first: ET.Element = decls[0]
        if first.tag == xstag("attributeGroup") or all(canonical(d) == canonical(first) for d in decls[1:]):
            clone: ET.Element = copy.deepcopy(first)
            clone.attrib.pop("use", None)
            return clone

        # Conflicting simple types (e.g. enum vs plain string): untyped accepts all.
        return ET.Element(xstag("attribute"), {"name": first.get("name") or ""})


def check_unknown_xsd11(root: ET.Element) -> None:
    for node in root.iter():
        if node.tag in XS11_ONLY:
            fail(f"unsupported XSD 1.1 construct: {node.tag}")


def strip_versioning(root: ET.Element) -> None:
    for node in root.iter():
        for name in [a for a in node.attrib if a.startswith(f"{{{VC}}}")]:
            del node.attrib[name]


def strip_asserts(root: ET.Element) -> None:
    parents: dict[ET.Element, ET.Element] = {c: p for p in root.iter() for c in p}
    for node in [n for n in root.iter() if n.tag == xstag("assert")]:
        parents[node].remove(node)


def merge_alternatives(root: ET.Element) -> None:
    merger = Merger(root)
    targets: list[ET.Element] = [
        e for e in root.iter(xstag("element")) if any(c.tag == xstag("alternative") for c in e)
    ]

    for elem in targets:
        label: str = elem.get("name", "?")
        if elem.get("type"):
            fail(f"element {label}: both type= and xs:alternative (unsupported)")

        alternatives: list[ET.Element] = [c for c in elem if c.tag == xstag("alternative")]
        names: list[str] = []
        for alt in alternatives:
            type_name: str | None = alt.get("type")
            if type_name is None:
                fail(f"element {label}: xs:alternative without type= (unsupported)")
            if type_name == "xs:error":
                continue  # the 1.1 schema rejects here; the lax 1.0 one cannot

            ctype: ET.Element | None = merger.ctypes.get(type_name)
            if ctype is None:
                fail(f"element {label}: unknown alternative type {type_name}")
            if has_wildcard_content(ctype):
                continue  # see module docstring: wildcards would break UPA
            if type_name not in names:
                names.append(type_name)

        for alt in alternatives:
            elem.remove(alt)

        if not names:
            fail(f"element {label}: no mergeable alternatives")

        elem.append(merger.merge(names))


def generate(src: Path) -> str:
    root: ET.Element = ET.fromstring(src.read_text())
    check_unknown_xsd11(root)
    strip_versioning(root)
    strip_asserts(root)
    merge_alternatives(root)
    ET.indent(root, space="  ")
    body: str = ET.tostring(root, encoding="unicode")
    return f'<?xml version="1.0" encoding="UTF-8"?>\n{HEADER.format(name=src.name)}{body}\n'


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    for name in SCHEMAS:
        out_path: Path = OUT / name
        out_path.write_text(generate(SRC / name))
        print(f"Wrote {out_path}")


if __name__ == "__main__":
    main()
